"""
generate_secrets.py — Run this once to create your .env file.

Usage:
  Windows:  python tools/generate_secrets.py
  Mac/Linux: python3 tools/generate_secrets.py

Requires PyNaCl:
  pip install PyNaCl
"""

import base64
import os
import secrets
import sys

sys.dont_write_bytecode = True

try:
    import nacl.signing
except ImportError:
    print("ERROR: PyNaCl is not installed.")
    print("Run:  pip install PyNaCl")
    sys.exit(1)

def b64(b):
    return base64.b64encode(b).decode()

jwt_secret       = b64(secrets.token_bytes(32))
server_hmac_key  = b64(secrets.token_bytes(32))
postgres_pw      = secrets.token_urlsafe(24)
redis_pw         = secrets.token_urlsafe(24)
signing_key      = nacl.signing.SigningKey.generate()
sign_key_seed    = b64(bytes(signing_key))
verify_key       = b64(bytes(signing_key.verify_key))

env_contents = f"""# fortispass — local demo environment
# Generated by generate_secrets.py — do NOT commit this file to git.

# Network
LISTEN_HOST=0.0.0.0
LISTEN_PORT=8080

# PostgreSQL
DATABASE_URL=postgresql://fortispass:{postgres_pw}@postgres:5432/fortispass
POSTGRES_PASSWORD={postgres_pw}

# Redis
REDIS_URL=redis://:{redis_pw}@redis:6379/0
REDIS_PASSWORD={redis_pw}

# JWT signing key
JWT_SECRET={jwt_secret}

# Ed25519 server signing key (seed)
SERVER_SIGN_KEY_SEED={sign_key_seed}

# HMAC key for recovery blob integrity
SERVER_HMAC_KEY={server_hmac_key}

# Deployment
SELF_HOSTED=true
RELAY_URL=http://localhost:8080
"""

output_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env")

if os.path.exists(output_path):
    print(f".env already exists at: {output_path}")
    answer = input("Overwrite it? This will break any running server. [y/N] ").strip().lower()
    if answer != "y":
        print("Aborted — existing .env kept.")
        sys.exit(0)

with open(output_path, "w") as f:
    f.write(env_contents)

print(f"\n.env written to: {output_path}")
print()
print("Server Ed25519 public key (pin this in the Android app at build time):")
print(f"  SERVER_VERIFY_KEY={verify_key}")
print()
print("Next step: see TUTORIAL.md — Part 1, Step 2")
